# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alberta Native Bee Council
email: brandon.allen@ualberta.ca
description: >- # this means to ignore newlines until "baseurl:"
  The website used for reporting the results from the ANBC 2018 monitoring program.
twitter_username: username
github_username: username
minimal_mistakes_skin: default
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Alberta Native Bee Council"
  avatar : "/assets/images/ANBC-logo.png"
  bio    : "2018 Monitoring Program."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.albertanativebeecouncil.ca/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/beallen/ANBC"
    - label: "ANBC"
      url: "https://www.albertanativebeecouncil.ca/"
    - label: "ABMI"
      url: "https://abmi.ca/"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/beallen/ANBC"
    - label: "ANBC"
      url: "https://www.albertanativebeecouncil.ca/"
    - label: "ABMI"
      url: "https://abmi.ca/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Implementation of comment section. Update comment the fields with the appropriate form information
comment-read: https://docs.google.com/spreadsheets/d/1b9YLX77q0WgZXS5F2cT3bJfZagjKXPDn3rbC0bsK4wU
comment-post: https://docs.google.com/forms/d/e/1FAIpQLSeQfC6CJULmYQ6m2TN8jSnhMIrowXoaE7hb7UXmhaeRdC0FMg
comment-post-fields: [ entry.1088208451, entry.224376209, entry.947085007]

google_forms_comments:
  lazy_load_comments: false
  chunked_comment_loading: false
  comment_replies_enabled: false
